# Project
site_name: cnb-tools
site_author: Verena Chung
site_description: >-
  Convenience tools/functions for challenges and benchmarking
  on Synapse.org

# Repository
repo_url: https://github.com/Sage-Bionetworks-Challenges/cnb-tools
repo_name: cnb-tools

# Navigation
nav:
  - cnb-tools: index.md
  - User Guide:
    - Introduction: user-guide/introduction.md
    - Cheat sheet: user-guide/cheat-sheet.md
    - Contributing: user-guide/contributing.md
  - Reference:
    - CLI: reference/cli.md
  - Changelog: 
    - changelog/release-notes.md
    - How to upgrade: changelog/upgrade.md

# Theme configuration
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      info: octicons/info-16
  logo: assets/favicon.png
  features:
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
- search
- mkdocstrings
- autorefs
- termynal:
    prompt_literal_start:
          - "$"
          - "(cnb-tools) $"

extra:
  social:
    - icon: octicons/home-16
      link: https://sagebionetworks.org/challenges-benchmarking/
    - icon: fontawesome/brands/github
      link: https://github.com/Sage-Bionetworks-Challenges/cnb-tools
    - icon: fontawesome/brands/docker
      link: https://github.com/Sage-Bionetworks-Challenges/cnb-tools/pkgs/container/cnb-tools
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cnb-tools/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
