blank_issues_enabled: false
contact_links:
  - name: Question or Problem
    about: Ask a question or ask about a problem in GitHub Discussions.
    url: https://github.com/Sage-Bionetworks-Challenges/cnb-tools/discussions/categories/questions
